- name: Remove Gemfile.lock
  file:
    path: "{{ app_dir }}/Gemfile.lock"
    state: absent

- name: Clone Rails app
  git: 
    repo: "https://github.com/yuta-ushijima/raisetech-live8-sample-app.git"
    dest: "{{ app_dir }}"
    version: main
    force: yes

- name: Run bundle install
  shell: bash -lc "bundle install"
  become: false
  args:
    chdir: "{{ app_dir }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.rbenv/shims:{{ ansible_env.HOME }}/.rbenv/bin:{{ ansible_env.PATH }}"

- name: Run yarn install
  shell: bash -lc "yarn install"
  args:
    chdir: "{{ app_dir }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ node_version }}/bin:{{ ansible_env.PATH }}"

- name: Create database.yml
  template:
    src: database.yml.j2
    dest: "{{ app_dir }}/config/database.yml"
    owner: ec2-user
    group: ec2-user
    mode: "0644"

- name: Run rails db:migrate
  shell: bash -lc "rails db:migrate"
  args:
    chdir: "{{ app_dir }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.rbenv/shims:{{ ansible_env.HOME }}/.rbenv/bin:{{ ansible_env.PATH }}"
