- name: Remove Gemfile.lock
  file:
    path: "{{ app_dir }}/Gemfile.lock"
    state: absent

- name: Clone Rails app
  git: 
    repo: "https://github.com/yuta-ushijima/raisetech-live8-sample-app.git"
    dest: "{{ app_dir }}"
    version: main
    force: yes

- name: Run bundle install
  become_user: ec2-user
  shell: |
    export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
    eval "$(rbenv init -)"
    bundle install
  args:
    chdir: "{{ app_dir }}"
    executable: /bin/bash

- name: Run yarn install
  become_user: ec2-user
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
    nvm use {{ node_version }}
    export PATH="$HOME/.yarn/bin:$PATH"
    yarn install
  args:
    chdir: "{{ app_dir }}"
    executable: /bin/bash

- name: Run rails db:migrate
  become_user: ec2-user 
  shell: bash -lc "rails db:migrate"
  args:
    chdir: "{{ app_dir }}"
  environment:
    PATH: "{{ ansible_env.HOME }}/.rbenv/shims:{{ ansible_env.HOME }}/.rbenv/bin:{{ ansible_env.PATH }}"