- name: Check rbenv installed
  become_user: ec2-user
  shell: bash -lc "rbenv -v"
  register: rbenv_exists
  changed_when: false
  ignore_errors: true

- name: Install rbenv
  become_user: ec2-user
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: "/home/ec2-user/.rbenv"
    update: no
  when: rbenv_exists is failed

- name: Check ruby-build installed
  shell: bash -lc "test -d ~/.rbenv/plugins/ruby-build"
  register: ruby_build_exists
  changed_when: false
  ignore_errors: true

- name: Install ruby-build plugin
  become_user: ec2-user
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "/home/ec2-user/.rbenv/plugins/ruby-build"
    update: no
  when: ruby_build_exists is failed

- name: Add rbenv PATH to bash_profile
  become_user: ec2-user
  lineinfile:
    path: "/home/ec2-user/.bash_profile"
    line: 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"'
    insertafter: EOF

- name: Add rbenv init to bash_profile
  become_user: ec2-user
  lineinfile:
    path: "/home/ec2-user/.bash_profile"
    line: 'eval "$(rbenv init -)"'
    insertafter: EOF

- name: Check Ruby {{ ruby_version }} installed
  shell: bash -lc "rbenv versions | grep {{ ruby_version }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: true

- name: Install Ruby {{ ruby_version }}
  become_user: ec2-user
  shell: |
    export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
    eval "$(rbenv init -)"
    rbenv install -s {{ ruby_version }}
    rbenv global {{ ruby_version }}
    rbenv rehash
  when: ruby_installed is failed
  args:
    executable: /bin/bash

- name: Check Bundler {{ bundler_version }} installed
  shell: bash -lc "bundler -v | grep {{ bundler_version }}"
  register: bundler_installed
  changed_when: false
  ignore_errors: true

- name: Install Bundler {{ bundler_version }}
  shell: |
    export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
    eval "$(rbenv init -)"
    gem install bundler -v {{ bundler_version }}
    rbenv rehash
  when: bundler_installed is failed
  become_user: ec2-user
  args:
    executable: /bin/bash

- name: Check Rails {{ rails_version }} installed
  shell: bash -lc "rails -v | grep {{ rails_version }}"
  register: rails_installed
  changed_when: false
  ignore_errors: true
  
- name: Install Rails {{ rails_version }}
  become_user: ec2-user
  shell: |
    export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
    eval "$(rbenv init -)"
    gem install rails -v {{ rails_version }}
    rbenv rehash
  when: rails_installed is failed
  args:
    executable: /bin/bash
