- name: Create config/puma.rb
  template:
    src: puma.rb.j2
    dest: "{{ app_dir }}/config/puma.rb"
    owner: ec2-user
    group: ec2-user
    mode: "0644"

- name: Create tmp/sockets directory
  file:
    path: "{{ app_dir }}/tmp/sockets"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"

- name: Create Puma systemd service file
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: "0644"

- name: Reloade systemd
  command: systemctl daemon-reexec

- name: Create Puma service
  systemd:
    name: puma
    enabled: yes
    state: started