- name: Create config/puma.rb
  template:
    src: puma.rb.j2
    dest: "{{ app_dir }}/config/puma.rb"
    owner: ec2-user
    group: ec2-user
    mode: "0644"

- name: Create tmp/sockets directory
  file:
    path: "{{ app_dir }}/tmp/sockets"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: "0755"

- name: Create Puma systemd service file
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: "0644"

- name: Reload systemd
  command: systemctl daemon-reload

- name: Create Puma service
  systemd:
    name: puma
    enabled: yes
    state: started

- name: Fix permission /home/ec2-user for nginx
  file:
    path: /home/ec2-user
    mode: "0755"

- name: Restart Puma
  become: true
  ansible.builtin.systemd:
    name: puma
    state: restarted
    enabled: true