- name: Update all packages
  become: true
  yum:
    name: "*"
    state: latest

- name: Install packages
  become: true
  yum:
    name:
      - git
      - make
      - gcc-c++
      - patch
      - libyaml-devel
      - libicu-devel
      - zlib-devel
      - readline-devel
      - libxml2-devel
      - libxslt-devel
      - ImageMagick
      - ImageMagick-devel
      - openssl-devel
      - libcurl
      - libcurl-devel
      - curl
    state: present